spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  datasource:
    url: jdbc:mysql://mysql-uavu.railway.internal:3306/railway?useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mail:
    host: ${SMTP_HOST:smtp.zeptomail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2

app:
  base-url: https://deallockecommercefullstackspringboot-production.up.railway.app
  admin-phones: ""

termii:
  base-url: ${TERMII_BASE_URL:https://api.ng.termii.com/api}
  api-key: ${TERMII_API_KEY:}
  sender-id: ${TERMII_SENDER_ID:}
  sms-channel: ${TERMII_SMS_CHANNEL:dnd}
  whatsapp-sender: ${TERMII_WHATSAPP_SENDER:}


server:
  forward-headers-strategy: native
  tomcat:
    max-part-count: 200
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: strict
