spring:
  application:
    name: backend
  devtools:
    restart:
      enabled: false
  flyway:
    enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/deallock?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:deallock}
    password: ${SPRING_DATASOURCE_PASSWORD:deallock_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  tomcat:
    max-part-count: 200
  port: 8080

app:
  base-url: http://localhost:8080
  admin-emails: ""
