ALTER TABLE deals
  ADD COLUMN IF NOT EXISTS item_photo_key VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS item_photo2_key VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS item_photo3_key VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS payment_proof_key VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS secured_item_photo_key VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS balance_payment_proof_key VARCHAR(500) NULL;

ALTER TABLE marketplace_items
  ADD COLUMN IF NOT EXISTS photo_key VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS photo2_key VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS photo3_key VARCHAR(500) NULL;

ALTER TABLE marketplace_orders
  ADD COLUMN IF NOT EXISTS payment_proof_key VARCHAR(500) NULL;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS profile_image_key VARCHAR(500) NULL;

