ALTER TABLE users
  ADD COLUMN phone VARCHAR(30) NULL;

ALTER TABLE deals
  ADD COLUMN payment_status VARCHAR(50) NULL,
  ADD COLUMN secured BIT(1) NOT NULL DEFAULT 0,
  ADD COLUMN secured_at DATETIME(6) NULL;
